robot:
  max_dist_tran: 5 # mm, maximum distance between set point and current pose.
  max_dist_rot: 0.05 # rad, maximum distance between set point and current pose.
  safety_mode: 1 # 0: none 1: truncate 2: stop
  operation_mode: 0 # 0: cartesian 1: joint
  safe_zone:
    xmin: -500
    xmax: 500
    ymin: 100
    ymax: 500
    zmin: 0
    zmax: 500

ftsensor:
  offset:
    fx: 2.84921
    fy: -2.05361
    fz: 2.0066
    tx: 0.186514
    ty: 0.316838
    tz: -0.00184363
  gravity:
    x: 0.0634656
    y: -0.0723191
    z: -1.83846
  COM:
    x: -0.000539253
    y: -7.31852e-06
    z: 0.0760828
  safety:
    fx: 30 # maximum: 20
    fy: 30 # maximum: 20
    fz: 60 # maximum: 60
    tx: 1.2 # maximum: 1
    ty: 1.2 # maximum: 1
    tz: 1.2 # maximum: 1
  transform_sensor_to_tool: # probe on tool changer
    x: 0 # meter
    y: 0
    z: 0.0927
    qw: 0
    qx: 0.7071
    qy: 0.7071
    qz: 0

##
## Device specific parameters
##
# ati netft
netft:
  ip_address: "192.168.1.1"
  sensor_name: "netft"
  frame_id: "end_effector"
  publish_rate: 1000
  print_flag: false
  file_path: "/usr0/home/yifanh/Git/catkin_ws/src/force_control/test/data/netft_data.txt"

# ABB EGM
egm:
  portnum: 6510
  print_flag: false
  file_path: "/usr0/home/yifanh/Git/catkin_ws/src/force_control/test/data/egm_data.txt"
